[package]
name = "kagome"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
axum = { version = "0.8.9", default-features = false, features = ["http1", "tokio"] }
axum-server = { version = "0.8.0", features = ["tls-rustls-no-provider"] }
base64 = "0.22.1"
bcrypt = "0.19.3"
ciborium = "0.2.2"
coset = "0.4.2"
jsonwebtoken = { version = "10", default-features = false, features = ["aws_lc_rs", "use_pem"] }
minijinja = "2.24.0"
p256 = "0.13.2"
qrcode = { version = "0.14.1", default-features = false, features = ["svg"] }
ring = "0.17.14"
schemars = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.10"
subtle = "2.6.1"
time = { version = "0.3.47", features = ["formatting"] }
tokio = { version = "1", features = ["net", "rt-multi-thread"] }
ureq = { version = "3.4", features = ["json"] }
