[package]
name = "kagome"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
base64 = "0.22.1"
ciborium = "0.2.2"
coset = "0.4.2"
htpasswd-verify = "0.3.0"
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
p256 = "0.13.2"
qrcode = { version = "0.14.1", default-features = false, features = ["svg"] }
ring = "0.17.14"
schemars = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.10"
time = { version = "0.3.47", features = ["formatting"] }
ureq = { version = "3.4", features = ["json"] }
