%%{init: {"htmlLabels": false, "flowchart": {"htmlLabels": false}}}%%
flowchart TD
    start[Request /credential-offer] --> method{GET?}
    method -- no --> not_found["`**HTTP 404** not found`"]
    method -- yes --> issuer["credential_issuer::validate"]
    issuer -- error --> error["`**HTTP 400** invalid_request`"]
    issuer -- ok --> generate["pre_authorized_code::generate"]
    generate -- error --> generation_error["`**HTTP 400** invalid_token_response`"]
    generate -- ok --> success["`**HTTP 200** credential offer`"]
